### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by JaberChowdhury** [JaberChowdhury/NextJs_project#8]
# html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <nav class="navbar">
      <div class="baglogo">
        <img width="62px" height="62px" src="./assets/logo.png" alt="" />
        <p class="scl">SCHOOL</p>
      </div>
      <div class="uldiv">
        <ul class="ulanchor">
          <li class="hometag"><a class="hafa-home" href="">Home</a></li>
          <li class="hometag"><a class="hafa-about" href="">About</a></li>
          <li class="hometag">
            <a class="hafa-facilities" href="">Facilities</a>
          </li>
          <li class="hometag">
            <a class="hafa-admission" href="">Admission</a>
          </li>
        </ul>
      </div>
      <i class="fa-solid fa-bars menuicon"></i>
      <div class="btndiv"><button class="btntag">Contact</button></div>
    </nav>
    <section>
      <div class="firstsec">
        <div>
          <p class="headline">
            <span class="emp">Empowering </span><br />
            students from small <br />age
            <span class="towards">towards vision</span>
          </p>
          <p class="dynamic">
            With the courage, Confidence, Creativity and Compassion to make
            <br />
            their Unique Contribution in a Diverse and Dynamic World.
          </p>
          <button class="enrollbtn">Enroll Now</button>
        </div>
        <div class="imgdiv">
          <img class="oneboy" src="./assets/hero-kids.png" alt="" />
        </div>
      </div>
    </section>
    <section>
      <div class="headingtwo">
        <h1 class="standard">Standard Curriculum</h1>
      </div>
      <div class="containerone">
        <div class="kinder">
          <img src="./assets/kinder.png" alt="" />
          <p class="years">Kinder (3-6) Years</p>
          <p class="yearsptag">
            Cum sociis natoque penatibus et magnis <br />
            dis parturient montes, nascetur ridiculus <br />
            mu sdis parturient
          </p>
          <a class="readone" href="">Read More</a>
        </div>
        <div class="elementary">
          <img src="./assets/elementary.png" alt="" />
          <p class="years">Elementary School</p>
          <p class="yearsptag">
            Cum sociis natoque penatibus et magnis <br />
            dis parturient montes, nascetur ridiculus <br />
            mu sdis parturient
          </p>
          <a class="readtwo" href="">Read More</a>
        </div>
        <div class="middle">
          <img src="./assets/middle.png" alt="" />
          <p class="years">Elementary School</p>
          <p class="yearsptag">
            Cum sociis natoque penatibus et magnis <br />
            dis parturient montes, nascetur ridiculus <br />
            mu sdis parturient
          </p>
          <a class="readthree" href="">Read More</a>
        </div>
      </div>
      <div class="arrows">
        <div class="icon">
          <i class="fa-solid fa-chevron-left"></i>
        </div>
        <div class="icon">
          <i class="fa-solid fa-chevron-right"></i>
        </div>
      </div>
    </section>

    <section class="section-story">
      <div class="oursec">
        <p class="psec">Our Stories</p>
      </div>
      <div class="thirdsection">
        <div class="firstdiv-container bg-white">
          <img class="storyoneimg" src="./assets/story-1.png" alt="" />
          <button class="storybtnone">November 19, 2019</button>
          <div class="twopdiv">
            <p class="classroom">
              A fun toddler coloring training on <br />
              classroom
            </p>
            <p class="yearsptag">
              Beautiful branding for changes by Never Now in Australia. <br />
              changes is a platform for open discussion in an inclusive and
              <br />collaborative environment, providing the...
            </p>
          </div>
        </div>

        <div class="smdivcontainer">
          <div class="last-div bg-white">
            <img src="./assets/story-2.png" alt="" class="smimg" />
            <button class="storybtnzero">November 19, 2019</button>
            <p class="smp">
              Find out if a school fits the <br />
              family’s needs
            </p>
          </div>
          <div class="last-div bg-white">
            <img src="./assets/story-3.png" alt="" class="smimg" />
            <button class="storybtntwo">November 19, 2019</button>
            <p class="smp">
              Summer math & literacy <br />
              centres for kids
            </p>
          </div>
          <div class="last-div bg-white">
            <img src="./assets/story-4.png" alt="" class="smimg" /><button
              class="storybtnthree"
            >
              November 19, 2019
            </button>
            <p class="smp">
              Classroom management <br />
              techniques for new tutors
            </p>
          </div>
          <div class="last-div bg-white">
            <img src="./assets/story-5.png" alt="" class="smimg" /><button
              class="smbtn"
            >
              July 19,2019
            </button>
            <p class="smp">
              Conversation rhymes <br />
              improve kids listening
            </p>
          </div>
        </div>
      </div>
      <div class="lastbtndiv"><button class="lastbtn">View All</button></div>
    </section>

    <footer>
      <div class="main-cotainer">
        <div>
          <div class="baglogo-2">
            <img class="bagimg" src="./assets/logo.png" alt="" />
            <p class="boldp">
              Kids <br />
              Education
            </p>
          </div>
          <p class="pizza">
            Pizza ipsum dolor meat lovers buffalo. <br />
            Deep dolor roll melted bacon Bianca pan <br />
            bacon pineapple Aussie. Mayo rib sauce <br />Hawaiian meatball.
          </p>
        </div>
        <div>
          <div class="licontainer">
            <p class="abscl">About School</p>
            <div class="footer-links">
              <li class="smli"><a href="" class="sma">Home</a></li>
              <li class="smli"><a href="" class="sma">About</a></li>
              <li class="smli"><a href="" class="sma">Facilities</a></li>
              <li class="smli"><a href="" class="sma">Admission</a></li>
            </div>
          </div>
        </div>
        <div class="fivecontainer">
          <div class="touch">Keep In Touch</div>
          <br />
          <div class="okbye">
            <img src="./assets/fb.png" alt="" class="smlogoimg" /><img
              src="./assets/dribble.png"
              alt=""
              class="smlogoimg"
            /><img src="./assets/twitter.png" alt="" class="smlogoimg" /><img
              src="./assets/google+.png"
              alt=""
              class="smlogoimg"
            />
          </div>
        </div>
      </div>
    </footer>
    <script
      src="https://kit.fontawesome.com/a6f9b8ef14.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

```

# css

```css
@import url("https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap");
* {
  /* border: 0.1px solid red; */
  font-family: "Quicksand", serif;
  font-optical-sizing: auto;

  font-style: normal;
}
button {
  cursor: pointer;
  border: none;
  outline: none;
  color: white;

  font-weight: 400;
}
body {
  /* max-width: 1190px; */

  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  /* gap: 50px; */
  background-image: url("./assets//bg.png");
  margin: auto;
  margin-left: 420px;
  margin-right: 420px;
}
nav {
  width: 100%;
}
.navbar {
  align-items: center;
  width: 100%;
  display: flex;
  justify-content: space-between;
}
.baglogo {
  justify-content: space-between;
  align-items: center;
  height: auto;
  width: auto;
  display: flex;
}
.uldiv {
  gap: 20px;
}
.hafa {
  font-size: 20px;
}
.hafa-home {
  text-decoration: none;
  font-size: 20px;
  color: orange;
}
.hafa-about {
  text-decoration: none;
  font-size: 20px;
  color: skyblue;
}
.hafa-facilities {
  text-decoration: none;
  color: rgba(5, 212, 223, 1);
  font-size: 20px;
}
.hafa-admission {
  text-decoration: none;
  font-size: 20px;
  color: rgba(93, 88, 239, 1);
}
.scl {
  font-weight: bold;
  font-size: 2rem;
}
.btndiv {
  display: flex;
}
.ulanchor {
  gap: 20px;
  display: flex;
}
.hometag {
  gap: 20px;
  list-style: none;
}
.btntag {
  border-radius: 12px;
  padding: 10px;
  background-color: orange;
  color: white;
  outline: none;
  border: none;
  line-height: 30px;
  font-size: 20px;
  font-weight: 400px;
}

.enrollbtn {
  padding: 10px;
  border-radius: 12px;
  background-color: black;
  color: white;
  font-size: 20px;
}
.towards {
  color: skyblue;
}
.dynamic {
  color: rgba(17, 17, 17, 1);
  font-size: 20px;
}
.emp {
  color: orange;
}
.firstsec > * {
  border: 1px dashed;
}
.firstsec {
  width: 100%;
  border: 1px dashed;
  justify-content: space-between;
  align-items: center;
  gap: 50px;
  display: flex;
}
.standard {
  text-align: center;
  font-size: 46px;
  font-weight: bold;
  color: #000000;
}
.headingtwo {
  text-align: center;
}
.headline {
  line-height: 61px;
  font-size: 56px;
  font-weight: bold;
}

.kinder {
  background: -webkit-linear-gradient(
    top,
    rgba(222, 245, 255, 1),
    transparent,
    transparent
  );
  /* background-color: rgba(222, 245, 255, 1); */
}
.years {
  color: rgba(32, 32, 32, 1);
  font-size: 25px;
  font-weight: bold;
}
.yearsptag {
  color: rgba(128, 128, 128, 1);
  font-size: 15px;
}
.elementary {
  background: -webkit-linear-gradient(
    top,
    rgba(255, 244, 220, 1),
    transparent,
    transparent
  );
  /* background-color: rgba(255, 244, 220, 1); */
}
.readone {
  color: rgba(100, 200, 255, 1);
  text-decoration: none;
  font-size: 15px;
  font-weight: bold;
}
.readtwo {
  color: rgba(240, 170, 0, 1);
  text-decoration: none;
  font-size: 15px;
  font-weight: bold;
}
.readthree {
  text-decoration: none;
  font-size: 15px;
  font-weight: bold;
  color: rgba(135, 0, 255, 1);
}
.middle {
  background: -webkit-linear-gradient(
    top,
    rgba(242, 232, 255, 1),
    transparent,
    transparent
  );
  /* background-color: rgba(242, 232, 255, 1); */
}
.containerone {
  gap: 30px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.kinder,
.elementary,
.middle {
  border-radius: 19px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  width: 370px;
  height: 480px;
}
.oursec {
  display: flex;
  text-align: center;
  justify-content: center;
  align-items: center;
}
.psec {
  font-weight: bold;
  font-size: 3rem;
}
.storyoneimg {
  border-top-left-radius: 16px;
  border-top-right-radius: 16px;
  width: 100%;
}
.firstdiv-container {
  /* display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center; */
  gap: 10px;
  height: 630px;
  margin-top: 15px;
  margin-left: 15px;
}
.thirdsection {
  height: 630px;
  height: auto;
  /* width: 1440px; */
  justify-content: center;
  align-items: center;
  display: flex;
  gap: 20px;
  position: relative;
}
.smp {
  font-weight: bold;
  font-size: 15px;
  line-height: 29px;
}
.storybtnone {
  width: 175px;
  height: 50px;
  display: block;
  position: absolute;
  margin-left: 30px;
  background-color: #3cd8e8;
  border-radius: 48px;
  margin-top: -30px;
}
.classroom {
  font-size: 24px;
  font-weight: bold;
  padding-top: 20px; /* line-height: 38px; */
  color: #000000;
}
.last-div {
  border-radius: 16px;
  position: relative;
}
.storybtnzero {
  font-size: 15px;
  color: white;
  margin-left: 20px;
  margin-top: -20px;
  border: none;
  width: 150px;
  height: 30px;
  position: absolute;
  background-color: #95b226;
  display: block;
  border-radius: 48px;
}
.storybtntwo {
  font-size: 15px;
  background-color: #5d58f0;
  color: white;
  position: absolute;
  display: block;
  border-radius: 48px;
  margin-left: 20px;
  margin-top: -20px;
  border: none;
  width: 150px;
  height: 30px;
}
.storybtnthree {
  font-size: 15px;
  background-color: #95b226;
  color: white;
  position: absolute;
  display: block;
  border-radius: 48px;
  margin-left: 20px;
  margin-top: -20px;
  border: none;
  width: 150px;
  height: 30px;
}
.smbtn {
  font-size: 15px;
  border: none;
  color: white;
  margin-left: 30px;
  margin-top: -20px;
  display: block;
  position: absolute;
  background-color: #95b226;
  width: 127px;
  height: 30px;
  border-radius: 48px;
}
.smdivcontainer {
  height: 613px;
  gap: 20px;
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  justify-content: center;
  align-items: center;
}
.smimg {
  border-top-left-radius: 16px;
  border-top-right-radius: 16px;
}
.twopdiv {
  top: 120px;
  gap: 20px;
  height: 250px;
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  flex-direction: column;
}
.lastbtn {
  padding: 10px;
  color: white;
  background-color: black;
  border-radius: 12px;
  font-size: 20px;
  font-weight: bold;
  height: auto;
  width: 150px;
}
.lastbtndiv {
  display: flex;
  justify-content: center;
  align-items: center;
}
.main-cotainer {
  background-color: #01acfd;
}
.bagimg {
  height: 81px;
  width: 70px;
}
.boldp {
  font-weight: bold;
  font-size: 42px;
  line-height: 39px;
  color: white;
}
.baglogo {
  display: flex;
  justify-content: center;
  align-items: center;
}
.abscl {
  color: white;
  font-weight: bold;
  font-size: 24px;
}
.smli {
  list-style: none;
}
.sma {
  text-decoration: none;
  color: white;
  font-size: 20px;
  font-weight: 400px;
}
.licontainer {
  gap: 30px;
}
.touch {
  color: white;
  font-weight: bold;
  font-size: 26px;
}
.fivecontainer {
  margin-top: -20px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: auto;
}
.smlogoimg {
  display: flex;
  justify-content: center;
}
.okbye {
  gap: 10px;
  display: flex;
}
.main-cotainer {
  display: flex;
  justify-content: space-evenly;
  align-items: center;
}

footer {
  width: 100%;
}

.arrows {
  display: flex;
  justify-content: center;
  align-items: center;
  color: white;
  gap: 10px;
}
.icon {
  background-color: orange;
  width: 50px;
  height: 50px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  font-size: 30px;
}
.pizza {
  line-height: auto;
  color: white;
  font-size: 20px;
}

.baglogo-2 {
  display: flex;
  align-items: center;
}

.section-story {
  width: 100%;
  padding-bottom: 50px;
  background: -webkit-linear-gradient(top, transparent, #fea10156);
}
.bg-white {
  background-color: white;
}

.navbar > .menuicon {
  display: none;
}
.imgdiv {
  display: flex;
  justify-content: center;
  /* width: 100%; */
  align-items: center;
}
@media only screen and (max-width: 576px) {
  body {
    width: 100%;
  }
  .uldiv {
    display: none;
  }
  .btndiv {
    display: none;
  }
  .navbar > .menuicon {
    display: block;
    margin-right: 20px;
    font-size: 30px;
  }
  .firstsec {
    flex-direction: column;
    gap: 20px;
    justify-content: center;
    align-items: center;
  }
  .firstsec {
    flex-direction: column-reverse;
  }
  .oneboy {
    width: 90%;
  }
  .scl {
    display: none;
  }
  .containerone {
    flex-direction: column;
    gap: 20px;
  }
  .firstdiv-container {
    display: none;
  }
  .smdivcontainer {
    width: 500px;
    gap: 0px;
    transform: scale(0.7);
  }
  .smdivcontainer > div {
  }
  .main-cotainer {
    flex-direction: column;
    gap: 20px;
  }
  .main-cotainer > div {
    width: 100%;
  }
  .fivecontainer {
    width: 100%;
    justify-content: left;
    align-items: flex-start;
    margin-top: 10px;
  }
  .footer-links {
    display: flex;
    justify-content: left;
    align-items: flex-start;
    flex-direction: column;
  }
  .arrows {
    display: none;
  }
}

```
